---
name: tox

on:
  push:
    branches:
      - "main"
      - "chore/smoke"
  pull_request:
    branches:
      - "main"
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tox:
    uses: abhikdps/team-devtools/.github/workflows/tox.yml@main

  test-devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install devcontainer cli
        run: npm install -g @devcontainers/cli

      - name: Execute cmd on Devcontainer
        run: |
          devcontainer build --workspace-folder ./tests/fixtures/collection/testorg/testcol
          devcontainer exec --workspace-folder ./tests/fixtures/collection/testorg/testcol adt --version

