---
name: tox

on:
  push:
    branches:
      - "main"
      - "devontainer-test"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tox:
    uses: abhikdps/team-devtools/.github/workflows/tox.yml@main
    with:
      node-version-file: .tool-versions
